services:
  mongodbi_db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
  custom_app:
    image: vikyath11/todo-app-artifactory:v12
    ports:
      - "3001:3001"

volumes:
  mongodb-data:
